### PR TITLE
Add junit support

### PR DESCRIPTION
**Pull request by MalloZup**
## description:

we will benifts for more sorting and  benifits for toaster.
Jenkins will give more meta-info about junit

## change for users:

for users we don't have any changes 

## need to do on jenkins-side:

- [ ] we need to export the file to the workspace then we are fine :rocket: 

@meaksh @dincamihai @brejoc 

I think we can change 'results.xml' to 'toaster_results.xml' or open for other names :rabbit: :smile:

### CODE REVIEW

**Comment by MalloZup** [comment]
thx @brejoc  we can wait @dincamihai  after his :sun_with_face: :beach_umbrella: :bikini:  no pb.

We might choose a good name atm so we don't change it later for the results.xml file thx

**Comment by MalloZup** [comment]
@dincamihai @brejoc thx
we can merge it! link

**Comment by dincamihai** [comment]
@MalloZup where do we need to set the name of the file?

**Comment by MalloZup** [comment]
@dincamihai  from my pov is nice like it is a now. If you want other beautiful names feel free to rename it. :+1:

**Pull request merged**
